### ISSUE TITLE
[solved]Doesn't work in Unity2018.2.2f1

### ISSUE THREAD

**Issue by wgcrown** [keijiro/Lasp#11]
Doesn't work in Unity2018.2.2f1

**Comment by keijiro** [comment]
Thanks for reporting. Could you provide information about the issue?

- Platform
- Error message/log

**Comment by wgcrown** [comment]
Platform:
Windows10 x64 Unity2018.2.2f with mono Backend
Error message/log:
There is no error message, but before I build it particles appear randomly and with no audio.
That happens when I use Resonance in the project.

**Comment by wgcrown** [comment]
I tried it, this doesn't work.
But I find more detail, Lasp could work with Google Resonance in the editor mode perfectly.
after build out, only Resonance could work.
Do you need a sample project? I can offer one.

**Comment by wgcrown** [comment]
I tested the same project in 2017.4.2, It works in both circumstances.

**Comment by wgcrown** [comment]
![tim 20180810155324](https://user-images.githubusercontent.com/31947897/43945702-8dc1f722-9cb5-11e8-80f8-529622d1500a.png)
![tim 20180810155242](https://user-images.githubusercontent.com/31947897/43945704-8e0345b0-9cb5-11e8-992e-42b1fcf1ec76.png)
![tim 20180810155255](https://user-images.githubusercontent.com/31947897/43945705-8e45cfe8-9cb5-11e8-94aa-d56b654f0fbb.png)
Here is my setting.

**Comment by wgcrown** [comment]
I tried building it in development mode and got some error message:
![tim 20180810160511](https://user-images.githubusercontent.com/31947897/43946263-53242480-9cb7-11e8-9fe4-29f022ea2110.png)

**Comment by keijiro** [comment]
Are you using the loopback version of LASP? I thought you're using the standard external audio version.

The loopback version is pretty experimental, and I have no idea what's happening inside it.

**Comment by wgcrown** [comment]
Yes, you right.
Sorry, I sent the wrong place.

I switch to the old LASP version, but got the same problem :(
![tim 20180810163445](https://user-images.githubusercontent.com/31947897/43947695-5341a9c0-9cbb-11e8-80eb-fe2c0c4a8d90.png)

**Comment by keijiro** [comment]
Okay. Thanks for the following up. From your inspection, I guess that the root cause of the problem is not in the audio system but in the plugin/build process of Unity.

Unfortunately, I don't have enough time for tackling this problem (it's a pretty new symptom to me, so I'm afraid I have to spend much time to solve it).

Could you report this to Google Resonance too? I doubt they can respond immediately, but still you can try.

**Comment by wgcrown** [comment]
DllNotFoundException: Lasp
  at (wrapper managed-to-native) Lasp.PluginEntry.ReplaceLogger(intptr)
  at Lasp.PluginEntry.SetupLogger () [0x00027] in C:\Users\Pola studio\Desktop\Lasp-loopback\Assets\Lasp\Internal\PluginEntry.cs:47 
  at Lasp.LaspStream..ctor () [0x00007] in C:\Users\Pola studio\Desktop\Lasp-loopback\Assets\Lasp\Internal\LaspStream.cs:19 
  at Lasp.AudioInput.Initialize () [0x00001] in C:\Users\Pola studio\Desktop\Lasp-loopback\Assets\Lasp\AudioInput.cs:65 
  at Lasp.AudioInput.UpdateState () [0x0000b] in C:\Users\Pola studio\Desktop\Lasp-loopback\Assets\Lasp\AudioInput.cs:84 
  at Lasp.AudioInput.CalculateRMS (Lasp.FilterType filter) [0x00001] in C:\Users\Pola studio\Desktop\Lasp-loopback\Assets\Lasp\AudioInput.cs:31 
  at Lasp.AudioInput.CalculateRMSDecibel (Lasp.FilterType filter) [0x00002] in C:\Users\Pola studio\Desktop\Lasp-loopback\Assets\Lasp\AudioInput.cs:39 
  at ParticleController.Update () [0x00007] in C:\Users\Pola studio\Desktop\Lasp-loopback\Assets\Test\ParticleController.cs:27 

here is outpu_log info, and I found this could make something different between editor and build out:
https://github.com/resonance-audio/resonance-audio-unity-sdk/blob/master/Assets/ResonanceAudio/Scripts/ResonanceAudio.cs

**Comment by wgcrown** [comment]
Hello,
I have fixed it.
It's very simple:)
After building the project, find AudioPluginLaspLoopback.dll or Lasp.dll in the project_name\project_name_Data\Plugins\ and put it into project_name\project_name_Data\Plugins\x86
![image](https://user-images.githubusercontent.com/31947897/43952619-0d80c1a6-9cc9-11e8-938c-b5a685c6b75a.png)
![image](https://user-images.githubusercontent.com/31947897/43952635-18ef35b8-9cc9-11e8-92a5-0c19adafead7.png)
