### ISSUE TITLE
[Question] GetSpectrumData

### ISSUE THREAD

**Issue by Soaryn** [keijiro/Lasp#12]
Is it possible to utilize the GetSpectrumData or an equivalent function with LASP. I have been trying to make a visualizer, and have managed to make one utilizing an AudioSource and the GetSpectrumData method, but have yet to actually figure out how to approach it with LASP. I am also trying to avoid GameObjects as I am using the new ECS. 

For the record, I have been using _audioSource.GetSpectrumData(_array, 0, FFTWindow.Hamming);

Biggest reason I need to use LASP is that the audio is coming in through externally to Unity.

**Comment by keijiro** [comment]
I prefer using a filter bank for audio analyzation instead of FFT. Adding FFT as an optional method would be nice, I don't have enough time for it though.

**Comment by soraryu** [comment]
Maybe this helps?
http://answers.unity.com/answers/1317336/view.html

**Comment by delgelato** [comment]
SpectrumData would be nice, even just the basic of it. From there we can extract it further ourselves like for pitch tracking. Very keen on Lasp mainly for the low latency, something Unity's can't do..

**Comment by keijiro** [comment]
Now LASP v2 supports FFT.
