### ISSUE TITLE
[Question] How is normalized level event implemented?

### ISSUE THREAD

**Issue by eliemichel** [keijiro/Lasp#14]
Hi Keijiro, sorry to open an issue for this, Lasp works great, but I tried to look at the code to see how the normalized level event is implemented and have some troubles understanding it. Could you point me to some relevant entry point or keyword? I would like to reproduce this behavior of letting the user select an arbitrary property of an object.
Thanks!

**Comment by keijiro** [comment]
I'm not sure if I understood your question correctly, but I think the keyword that you're looking for is "UnityEvent". Google it. You can find some articles and YouTube videos about it..

**Comment by eliemichel** [comment]
Oh perfect that's what I was looking for! I was not aware that this was a feature of Unity.
