### ISSUE TITLE
Lasp not working with  with unity 2019.1.8f1 

### ISSUE THREAD

**Issue by fdiba** [keijiro/Lasp#16]
Hello I get this message when I open any scene:

"Rebuilding Library because the asset database could not be found!"

And then when I try to execute them nothing happen. Any idea ?

**Comment by keijiro** [comment]
> "Rebuilding Library because the asset database could not be found!"

This is not an error. You can simply ignore it.

Please check if your default audio input device is properly set up.

**Comment by fdiba** [comment]
Indeed it was a microphone problem. Thank you again!

**Comment by rdurnin** [comment]
Does Lasp require a microphone for audio input?

**Comment by keijiro** [comment]
@rdurnin You can use any type of audio input device.

**Comment by rdurnin** [comment]
Should Lasp automatically find a connected device and attach it? I have been unable to see line-in connected inputs, nor was I able to use the Microphone class to detect the stream.
