### ISSUE TITLE
[Question] Audio UI missing 

### ISSUE THREAD

**Issue by jieliou** [keijiro/Lasp#18]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/SNRfyRC"><a href="//imgur.com/a/SNRfyRC">Missing</a></blockquote>
Hi Keijiro. I have a UI missing issue like the image link above, and of course there has no audio incoming. I installed both Unity 2019.1 and 2019.2 and all the versions of Lasp, all the same results. 
I'm not sure if I installed package incorrectly or it relate to my computer issue. 
Do you have any idea? Thanks for help!

**Comment by keijiro** [comment]
Is it missing while play mode? (The level meter doesn't work while edit mode)

**Comment by jieliou** [comment]
Oh, it's working in play mode. Thanks for your time for this silly question!
