### ISSUE TITLE
parameterValue question 

### ISSUE THREAD

**Issue by jieliou** [keijiro/Lasp#19]
https://imgur.com/a/PTjv4sF
Hi Keijiro, I'm sorry for opening up another question. I took Vfx Controller from your LaspVfx project, but it seems missing parameterValue like the image attached. 
Is it related to the Unity version? Or I just have to roll back to Unity 2019.1 in my own project.

**Comment by keijiro** [comment]
This is a known issue of Unity: https://issuetracker.unity3d.com/issues/events-generated-by-the-player-input-component-do-not-have-callbackcontext-set-as-their-parameter-type

(The title only mentions non-public fields, but actually it affects public fields too)

P.S. This issue should be sent to the LaspVfx repository. Please re-check if you're referring a correct repository when reporting an issue.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
