### ISSUE TITLE
How to ensure that LASP is hearing the default device?

### ISSUE THREAD

**Issue by mr-brooks-dev** [keijiro/Lasp#20]
Hello. I've been thoroughly testing LASP on different computers and different audio setups and I keep running into the issue of LASP not hearing anything from the default audio device. 
What can I do to track down this problem? 
I need a surefire way to make sure that LASP will hear the audio coming from the default device and if it isnt how to reliably fix that issue..
I would love it if LASP would let me choose the audio device - to ensure its working but Im sure you have reasons for making it default only. 
Thanks in advance for your advice/help.
-VJ Anomolee

**Comment by vjanomolee** [comment]
In all of these scenarios where there is nothing coming through the LASP Audio input script I am able to hear the audio and confirmed it is listed as the default audio device.  Do I need to restart windows if the default audio device was changed and then changed back?  I'm really struggling trying to find out why LASP cant hear the signal..  :-(
