### ISSUE TITLE
EntryPointNotFoundException: LaspReplaceLogger with Unity 2019.3.0b7

### ISSUE THREAD

**Issue by mikavaliviita** [keijiro/Lasp#21]
Hi!

When opening my project using LSAP with Unity 2019.3.0b7, I get this error:

**EntryPointNotFoundException: LaspReplaceLogger**

When trying to do this:

`var peak = Lasp.MasterInput.GetPeakLevelDecibel(_filterType);`

Also, with 2019.3.0b7, the Windows plugin DLL had to be renamed, because the name conflicted with the asmdef file.

**Comment by mikavaliviita** [comment]
This works fine with 2019.2.10f1 if the Windows plugin DLL is renamed back to the original name.

It seems the renaming is the problem here.

Here is the full log entry of the error:

```
EntryPointNotFoundException: LaspReplaceLogger
Lasp.PluginEntry.SetupLogger () (at Assets/Lasp/Runtime/Internal/PluginEntry.cs:51)
Lasp.LaspStream..ctor () (at Assets/Lasp/Runtime/Internal/LaspStream.cs:19)
Lasp.MasterInput.Initialize () (at Assets/Lasp/Runtime/LaspCommon.cs:71)
Lasp.MasterInput.UpdateState () (at Assets/Lasp/Runtime/LaspCommon.cs:90)
Lasp.MasterInput.GetPeakLevel (Lasp.FilterType filter) (at Assets/Lasp/Runtime/LaspCommon.cs:23)
Lasp.MasterInput.GetPeakLevelDecibel (Lasp.FilterType filter) (at Assets/Lasp/Runtime/LaspCommon.cs:31)
mytest01.Update () (at Assets/mytest01.cs:174)
```

**Comment by keijiro** [comment]
Name conflict should be fixed.

I think it can be worked around by renaming asmdef instead of renaming the plugin dll.

**Comment by mikavaliviita** [comment]
Yes, already tried it with 2019.2.10f1 and it works. Will verify this with 2019.3.0b7 also ASAP.

**Comment by mikavaliviita** [comment]
With Unity 2019.3.0b7, renaming the asmdef file still gives the following error, but it seems to be working:

```
Plugin 'Assets/Lasp/Plugin/Windows/x64/Lasp.dll' has the same filename as Assembly Definition File 'Assets/Lasp/Runtime/LaspAsmDef.asmdef'. Rename the assemblies to avoid hard to diagnose issues and crashes.
```

**Comment by keijiro** [comment]
This issue was fixed in v2.
