### ISSUE TITLE
Unable to select inputs when using package

### ISSUE THREAD

**Issue by medcelerate** [keijiro/Lasp#25]
It appears that the available Audio Level Tracker script included in the unity package does not have the serializable fields for selecting the input device like the laspvfx demo has. Was this intended or is it something that needs to be added manually?

**Comment by keijiro** [comment]
Did you use the "v2" branch? The "master" branch contains the old version of LASP that doesn't have the device selector.

**Comment by medcelerate** [comment]
Yes I used the releases under the V2 branch.

**Comment by keijiro** [comment]
Sorry, I overlooked some sentences in the first post. You shouldn't use the `.unitypackage` file. This package has migrated to Unity Package Manager from the legacy `.unitypackage` way. Please read the "How to install" section in the README.md.
