### ISSUE TITLE
Possible to build for Windows?

### ISSUE THREAD

**Issue by smangiat** [keijiro/Lasp#27]
Hi, Is it possible to build LASP for windows?  When I try to build I get errors related to SoundIO. I also included SoundIO in my packages json. 

``Library\PackageCache\jp.keijiro.lasp@2.1.2\Runtime\Internal\InputDeviceHandle.cs(28,16): error CS0246: The type or namespace name 'SoundIO' could not be found (are you missing a using directive or an assembly reference?)``

Thank you very much! This package is really great.

**Comment by keijiro** [comment]
LASP does support Windows build. Could you clarify the following points?

- Did it work on Unity Editor?
- Did you build the project for x64 (64-bit) architecture? LASP doesn't support x86 (32-bit).

**Comment by smangiat** [comment]
Ah yes I was trying to build for x86. I was able to get it working after switching to x64, and then upgrading the burst compiler to the latest version 1.30. Thanks very much, I appreciate the quick help!
