### ISSUE TITLE
Realtime Microphone Playback

### ISSUE THREAD

**Issue by TipVFL** [keijiro/Lasp#29]
I am trying to achieve a low latency playback of microphone input in Unity and multiple places pointed me towards LASP but I cannot figure out any way to playback the audio it is monitoring. 

I looked through closed issues and found two related to this, #24 and #8, however I did not see a solution posted. Issue 8 was merged into issue #2 which was closed, but issue 2 was not about microphone playback, it was about using a file as input.

If there is a way to playback LASP's input, please let me know how. It would be incredibly helpful to me.

Thank you.

**Comment by keijiro** [comment]
LASP only provides the low latency audio input functionality. It doesn't support output.

You can use the combination of LASP input and Unity's built-in output, but it will be affected by the latency of the built-in output.

**Comment by Felix-N** [comment]
@keijiro I'm looking for the same, low latency input and output.

Could you point me into the direction of how to use use it with the unity built in output system?

And do you know the amount of latency added there / how to control it?
