### ISSUE TITLE
android/ios version possible?

### ISSUE THREAD

**Issue by mechpil0t** [keijiro/Lasp#30]
would it be possible to get an android/ios version of this?

**Comment by keijiro** [comment]
LASP uses [libsoundio](https://github.com/andrewrk/libsoundio) as a backend. At the moment, libsoundio only supports the desktop platforms (Windows, macOS, Linux), and that's why LASP only supports them. If libsoundio gets mobile support, it will be possible to add mobile support to LASP too.
