### ISSUE TITLE
Installing on Unity 2019.4.5

### ISSUE THREAD

**Issue by th-ink** [keijiro/Lasp#31]
Excuse my noobness, but how can I install the package in Unity? I've tried cloning the repo, editing the `manifest.json`  found in `Packages/`  as per instructions in the README. But when I run the scene in Unity, I get `error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)` errors. I've also tried to create a new project and then install the package from package manager by adding the local file `Packages\jp.keijiro.lasp\package.json` but that doesn't work either.
Thanks

**Comment by keijiro** [comment]
Fixed: https://github.com/keijiro/Lasp/commit/575306647361e4e6ee9582773ac270cbed5f1a06

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if it still reproduces.
