### ISSUE TITLE
PropertyBinders

### ISSUE THREAD

**Issue by jdk-21** [keijiro/Lasp#32]
Hey, I'm pretty knew to Unity and C# and after some experiments with LASP I encountered a problem.
I have three GameObjects: an AudioHandler and two spheres. The AudioHandler has a script that creates an AudioLevelTracker like in the DeviceSelector example.
I also have a script for the spheres. From there I want to add PropertyBinders to this AudioLevelTracker and I have no idea how to accomplish this. Is there an easy way to do this?

**Comment by keijiro** [comment]
Try adding `PropertyBinder` using `AddComponent`, then set `Target`, `PropertyName`, `Value0` and `Value1`. These fields are public, so you can access them from your script.

https://github.com/keijiro/Lasp/blob/v2/Packages/jp.keijiro.lasp/Runtime/PropertyBinder.cs

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by Fenikkel** [comment]
I'm trying to use _FloatPropertyBinder_ but _No Single property found_ alert appears.

As a _Target_ I'm using a script that have a **public float**  and also a **public System.Single**. Any of these types seems good for the binder.

Sorry for my ignorance but what I'm doing wrong?

Edit: It only accepts Unity components public variables?

**Comment by keijiro** [comment]
@Fenikkel You also have to provide a public property along with a public variable.

**Comment by Fenikkel** [comment]
Than you Kejiro 🥇 

For noobs like me, what Kejiro means is this:

```
    public float _FloatForBinder;
    public float FloatForBinder
    {
        get => _FloatForBinder;
        set
        {
            _FloatForBinder = value;       
        }
    }
```

[Microsoft docs](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties)
