### ISSUE TITLE
Is there a way to use system audio?

### ISSUE THREAD

**Issue by DanielEliasib** [keijiro/Lasp#33]
I'm trying to create an audio visualizer in Unity and a I stumble with this. 

The demos work really well but I was wondering if there is a way to use the system audio? I saw this [issue](https://github.com/keijiro/Lasp/issues/2) and I'm using the Stereo Mix option to get by, but as it says there, not everyone has that option activated. So I was wondering if there is a way to use the system audio. Do I have to create a fake input device and somehow route the sound trough there?

Also I tried to use the Loopback branch but I couldn't get it to work, I guess it doesn't work with Lasp v2?

Thank you.

**Comment by keijiro** [comment]
First of all, I assume you're asking how to capture system audio **OUTPUT** (it's quite easy to capture the system audio input).

> So I was wondering if there is a way to use the system audio.

There is no way to capture the system audio output.

> Do I have to create a fake input device and somehow route the sound trough there?

Yes.

> Also I tried to use the Loopback branch but I couldn't get it to work, I guess it doesn't work with Lasp v2?

That's an experimental branch of Lasp v1. I abandoned the branch.
