### ISSUE TITLE
VFX Property Bindings are not available in 2020.2.0f1

### ISSUE THREAD

**Issue by MrMahgu** [keijiro/Lasp#35]
LASP does not show up in the context menu for attaching property bindings for VFX Property Binder (script) component.

I am not skilled enough to understand how to fix, sorry.

Unity Version: 2020.2.0f1

**Comment by MrMahgu** [comment]
Oops, too quick to post -- solved.

**Comment by agunay** [comment]
Hi, @MrMahgu can you please explain how you solved this? I'm having the same issue after upgrading to Unity 2021.1.12f1 - LASP doesn't show up on VFX Property Bindings list,. it was working perfectly on 2019 version

**Comment by agunay** [comment]
Realised I was missing LaspVFX package 🤦
