### ISSUE TITLE
Thank you!   I am still having an issue installing LASP into Unity 2020.1.

### ISSUE THREAD

**Issue by JeffDobrow** [keijiro/Lasp#41]
Thank you!   I am still having an issue installing LASP into Unity 2020.1. I was unsure/unable how to 'reopen' previous issue.

I wish I understood more of all this...apologies. 

*I edited the manifest.json package as described.
1 - If I Open your test project then everything works and I notice that libsoundio is fully installed in packages

2 - If I attempt to install the package.json from the Package Manager it will not install and gives me an error related to "missing libsoundio as a dependency"

3 - I have tried installing Libsoundio first, and that then gives me a similar error through package manager regarding another dependency...lol!

I would love the ability to import and use some of these together however really do run into a lot of issues, definitely learning!  Thank you for any insight.

_Originally posted by @JeffDobrow in https://github.com/keijiro/Lasp/issues/40#issuecomment-778805374_

**Comment by keijiro** [comment]
I'm closing this issue as duplicated.
