### ISSUE TITLE
Conflicting assemblies with Unity's collections package

### ISSUE THREAD

**Issue by emilianavt** [keijiro/Lasp#42]
`org.nuget.system.memory` has a dependency on `System.Runtime.CompilerServices.Unsafe`, which it also retrieves from nuget, but there is already an incompatible version of this assembly included with `com.unity.collections` as installed through Unity's package manager to satisfy the dependencies of some other assets in my project. Having the same assembly at twice at different versions does not seem to be possible. I tried manually removing the assembly installed from nuget, but then System.Memory became unable to load it, although the one from the collections package was in the project.

Is there any way to resolve this conflict?

**Comment by keijiro** [comment]
Which version are you using? As far as I tried, it didn't reproduce with the latest version (0.15.0-preview.21). I think this issue was fixed in Collections 0.11.0.

**Comment by emilianavt** [comment]
Thank you for your response! I'm on Unity 2019.4.16f1 and Collections 0.9.0-preview.6. I assumed that it was the latest version of the package, because Unity shows it as up to date, but I see now that newer versions are available for Unity 2020.

**Comment by keijiro** [comment]
Thanks for the clarification. I'm closing this issue now as resolved (on the Collections side). Please feel free to reopen it for further problems.
