### ISSUE TITLE
Install error: "Failed to resolve packages"

### ISSUE THREAD

**Issue by jeffhgit** [keijiro/Lasp#47]
Following the install directions by pasting the text in my manifest.json, I get the following error, "Failed to resolve packages: The file is not valid JSON: Unexpected string in JSON at position 447 while parsing..."

It seems to run into an error after the 'n' in "name", but the actual text I pasted is:

"{
  "scopedRegistries": [
    {
      "name": "Unity NuGet",
      "url": "https://unitynuget-registry.azurewebsites.net",
      "scopes": [
        "org.nuget"
      ]
    },"

I'm using Unity ver. 2020.3.22. Am I missing a step?

![image](https://user-images.githubusercontent.com/87553869/145474726-a22df8f6-5b56-4b2e-9f37-fd3b2d5bc8df.png)

**Comment by keijiro** [comment]
Could you attach your edited `manifest.json` file?

**Comment by jeffhgit** [comment]
[manifest.txt](https://github.com/keijiro/Lasp/files/7697909/manifest.txt)

Had to change the extension to upload.

**Comment by keijiro** [comment]
There are missing trailing commas in there lines:

```
    "com.unity.modules.uielements": "1.0.0"
    "jp.keijiro.lasp": "2.1.5"
```

**Comment by jeffhgit** [comment]
I got it, thank you! It's working with microphone input, but is there way to use it to analyze a playing AudioSource component? My goal is to monitor an audio stream, get typical volumes/frequencies, and be able to detect spikes in volume or certain frequencies to trigger an effect elsewhere. Is this something LASP can be used for? I'm currently using Unity's AudioSource.GetOutputData but it's not ideal, and I want something like LASP's LevelMeter.

**Comment by keijiro** [comment]
> is there way to use it to analyze a playing AudioSource component?

No, LASP doesn't support internal audio sources.

> Is this something LASP can be used for?

Detecting spikes (musical onset) is a SUPER hard problem, especially with mix-downed musical tracks. LASP only analyzes loudness level of specified frequency bands. Don't expect that it magically detects "spikes".

**Comment by keijiro** [comment]
I'm closing this issue now as the original question was solved. Please feel free to reopen it for further problem on the original topic.
