### ISSUE TITLE
Minimizing latency?

### ISSUE THREAD

**Issue by jeffhgit** [keijiro/Lasp#48]
I'm wondering if there's a way to minimize latency within LASP. There is still a bit of lag in my response, maybe ~200ms. Are there any alterations I can make to LASP to lower this? Maybe some LASP features or components that I can disable or reduce to cut down on the resource cost/response time? Thank you.

**Comment by keijiro** [comment]
LASP chooses the buffer size based on the following calculation: `max ( 1/60, device driver latency )`

https://github.com/keijiro/Lasp/blob/v2/Packages/jp.keijiro.lasp/Runtime/Internal/InputDeviceHandle.cs#L186

So, if your device supports low latency input with the default device driver on your system, it should run with 1/60 sec latency.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
