### ISSUE TITLE
Crash when no audio interface is available 

### ISSUE THREAD

**Issue by keijiro** [keijiro/Lasp#5]
Unity crashes in a hard way when no audio interface is available. It should handle the exception in a proper way and continue running without audio input.

This issue is originally reported in the KalkLASP project. https://github.com/keijiro/KlakLasp/issues/2

**Comment by johnnyjr** [comment]
I know this is quite old, but will this be solved? We are using it in a project where we get hard crashes if the user doesn't have an input interface.

**Comment by keijiro** [comment]
Fixed in v1.0.0
