### ISSUE TITLE
Planned to be available on iOS?

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [keijiro/Lasp#50]
Hi Keijiro !

Your lib seems to be very great (I tested the `loopback` branch which is work with AudioSource and then with Microphone).
I really need this lib but under iOS, are you planning to build it for iOS ? Or maybe I can do it (if I could have a confidential access to the native sources of course ..).

Let me know ;) ,
Thanks in advance,
Regards, 
Eric

**Comment by keijiro** [comment]
> are you planning to build it for iOS ?

No.

> Or maybe I can do it (if I could have a confidential access to the native sources of course ..).

The source code is totally open. There is no restriction.

**Comment by keijiro** [comment]
I"m closing this issue now. Please reopen it for further problems.
