### ISSUE TITLE
How can I leave the Audio listener?

### ISSUE THREAD

**Issue by leessunj** [keijiro/Lasp#51]
Hello, thanks for the nice plugin.
I have a question!
Audio listener is not available while using this plugin.
When I enter play mode, it disappears altogether, so I can't play the current input value or other example audio file.
I've seen that OUTPUT is not possible in a previous issue. But is it also impossible to listen to a pre-given sample file rather than listen to the real-time input again?

I use unity 2020.3.25f1, and the warning message is like this.
![image](https://user-images.githubusercontent.com/77258405/151278426-2488e056-1fde-4c93-bb99-6d8500460a6b.png)

**Comment by keijiro** [comment]
> Audio listener is not available while using this plugin.

No. I removed the built-in audio module from the sample project for simplicity, but you can use it in your project. Or you can re-add the built-in module from Package Manager on the sample project.

**Comment by keijiro** [comment]
I'm closing this issue as "not reproducible". Please reopen it for further problems.
