### ISSUE TITLE
Lasp scripts only see a small number of existing parameters

### ISSUE THREAD

**Issue by MissCalculated** [keijiro/Lasp#55]
Hi! Thank you again for all your tools.

I have recently started using Lasp.

Lasp's Property Binders only seem to find a few properties of the target object. Transform, rotation, scale + a couple other random ones like lightmap scale. It will see my own scripts, yet it won't see the basic public Vector3 or floats I put in them.

Is it possible for a user to write a script to use the Lasp volume output to affect parameters? Instead of using the Property Binders. If so, you have any tutorial or guide on what code to use for the output of Audio Level Tracker or Spectrum Analyzer?

For example, I'm hoping to use Audio Level Tracker to affect parameters in a material. Right now, I'm trying to have the audio modify the emission color/intensity. If I add a Property Binder for Color, it won't see any parameters on any component.

Do you have any advice? If I am misunderstanding the Proper Binders, please let me know.

Thank you!

**Comment by keijiro** [comment]
Please check #53

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.

**Comment by MissCalculated** [comment]
Thank you! Got it to work.
