### ISSUE TITLE
Custom filter frequencies

### ISSUE THREAD

**Issue by MissCalculated** [keijiro/Lasp#56]
Hi --

Is there a way, even by editing the script, that I could set the Audio Level Tracker filter frequencies/cutoffs more specifically?

If not, may I request that as a feature? It's quite important in the visual work I do outside of Unity, and I'm trying to incorporate those workflows into Unity as well.

ありがとう！

**Comment by keijiro** [comment]
You can change the filter parameters.

https://github.com/keijiro/Lasp/blob/v2/Packages/jp.keijiro.lasp/Runtime/Internal/LevelMeter.cs#L54

I think it's not enough for precise control, though.

Please understand that the main aim of the multi-band filter embedded in LASP is just providing a quick solution for non-serious projects. I know just adding a single bandpass filter is not enough for detecting meaningful information from a mixed-down track. I usually use external solutions like DAW+VZO for practical projects.

https://github.com/keijiro/vzo

**Comment by MissCalculated** [comment]
Ah gotcha. I'll play with that line of code and see how it goes.

(I'm very new to coding, though I'm doing well!)

I do visuals to live audio and I would prefer to not run a DAW just for audio routing, to avoid using extra computer resources and potentially bogging down multiple instances of Unity + Resolume + Wire.

If I can make this work with Lasp it'll be perfect. I can use multiple Audio Level Trackers with different cutoffs and filter types. That will certainly work well enough for me.

Thanks! I'll let you know how it goes.

**Comment by MissCalculated** [comment]
I've tried my best and now I'm back for help. When I make changes to your scripts, they are overwritten by LASP, and that goes beyond my coding knowledge.

Do you know how I could expose the filter cutoff number for use in the UI? My goal is to be able to set each Audio Level Tracker to a different cutoff. This would cover all my needs I think!

(I'm not sure DAW+VZO would work for me, since I want to respond to any incoming audio from many different artists, rather than MIDI/OSC.)

**Comment by keijiro** [comment]
Are you trying to modify the script files in `Library/PackageCache`? Changes in the cache directory will be reverted by the package manager. You have to put the package files in `Packages` directory as I did in this repository.

> Do you know how I could expose the filter cutoff number for use in the UI? 

The honest answer is "I don't know either". It would need some modifications to both the runtime / editor code. I haven't touched this project for over two years. I would have to start over from reading the code (because I forgot most part of the code).
