### ISSUE TITLE
Missing SoundIO namespace

### ISSUE THREAD

**Issue by Mutoxicated** [keijiro/Lasp#69]
1. I am on windows
2. It is not working in the Unity Editor.

What do I do?

**Comment by keijiro** [comment]
Could you share the editor log file?

https://docs.unity3d.com/Manual/LogFiles.html

**Comment by Mutoxicated** [comment]
[Here](https://github.com/user-attachments/files/16433211/Editor.log)

**Comment by keijiro** [comment]
It seems that you have installed the package in a wrong way. Please check the "How to Install" section in README.
