### ISSUE TITLE
Particles test rms and level negative values

### ISSUE THREAD

**Issue by friken** [keijiro/Lasp#7]
I'm looking at the two test scenes and the test w bars and lines works as expected. The particles test is not working. No particles are displayed when running it w/ music playing. note: Windows, Unity 5.6.2.

        var rms = Lasp.AudioInput.CalculateRMSDecibel(_filterType) + _amplify;
        var level = 1 + rms * 0.1f;

        _emission.rateOverTime = Mathf.Clamp01(level * 5) * _originalEmission;
        _shape.radius = Mathf.Clamp01(level) * _originalRadius;
        Debug.Log("rms=" + rms);
        Debug.Log("level=" + level);

note the debugs show negative rms and level values, so setting a 0-?? particle setting like rateovertime and radius to a negative value just sets it to 0.

output sample from debug:
rms=-30.09703
level=-2.009703

not sure exactly what the rms and level values are returning to correct the issue.

**Comment by keijiro** [comment]
CalculateRMSDecibel returns audio levels in dB (decibel), so the range of the value is from -inf up to 0.0 (or 3.0).

https://en.wikipedia.org/wiki/VU_meter

I guess that the audio input level is too low. How about increasing the volume a bit more?

**Comment by friken** [comment]
Thanks for the response.... It was most likely volume. Looking at the other demo, I was able to sort out what I needed to use LASP in my project. I LOVE IT! However.... I kinda screwed up and missed a very important tidbit... For context, it will help if you knew what I'm using it for:

https://clips.twitch.tv/CulturedImpossibleTroutMcaT

This project is for VR and DJ/VJ visualization and uses music spectrum data to drive fractal math for raymarched realtime visuals. When using unity to play songs directly, that all is easy to do... but of course everyone that I show it to wants to feed in their own music... ideally they want to just setup their Spotify/soundcloud/DJsoftware etc to play whatever and have my fractal thing just use whatever their machine is playing through other software. So... I started looking around for a way to do that. FMOD was the first thing I found but stumbled trying to use it directly in Unity. I found a nice FMOD wrapper for Unity called AudioStream. It allowed for grabbing the windows output/input device and piping it through a Unity audiosource. I used it and the audiosource spectrum data. The issues I faced was:

1. the latency was pretty bad....and worst part was it wasn't consistent latency. Sometimes it was almost good enough... other times it would stretch into 200-500ms+ latency making it worthless.

2. To make it work at all it had to be jury rigged by setting windows output to a non-used audio device... the component to pull from that device... then Unity/FMOD set to output to the actual speakers so that what was showing on the screen was accurate and not so lagged... some computers could do this setup... some can't.

So.... long story... but something really silly happened when using LASP. I TOTALLY missed that LASP is only grabbing the default INPUT device. I integrated LASP and it was AMAZING! no latency at all that I could notice. The three band high/mid/low gave me better data than what I was doing w 5-10 bands myself through a unity audiosource. I spent a full day redoing all my code for LASP... I loved it so much I even did final cleanup and removed all the old Audiosource code (yeah I have old backups...but..). After being super proud of the results I turned down my speakers and noticed that the fractals and lighting that the music drives diminished and then it hit me..... DAMNIT it's grabbing my mic NOT my audio device output! At first I didn't believe it because the data used was without lag and was clean enough to perfectly drive things w the three bands -- very precisely. Good mic I guess... And really.... I spent a full day of dev without changing my volume at all!? lol... that will be fun redoing all my min/max ranges once I get the raw full volume audio device output. 

Silly me.... now I've spent a day looking at the internals of LASP trying to get it to stream from the default audio OUTPUT device instead of input device. 

I tried this:

            auto deviceInfo = Pa_GetDeviceInfo(Pa_GetDefaultOutputDevice());

            PaStreamParameters paramsIn;
            paramsIn.channelCount = 2;
            paramsIn.device = Pa_GetDefaultOutputDevice();
            paramsIn.hostApiSpecificStreamInfo = nullptr;
            paramsIn.sampleFormat = paFloat32;
            paramsIn.suggestedLatency = deviceInfo->defaultLowInputLatency;

but I get an error something like invalid channel count from portaudio. I tried 0,1,2,3,4 for channel count. debugged the channel count of the device itself and used that #... nothing is working to get it to stream from the default audio output device. Any ideas?

Sorry to post this here... not where else to send you a msg. Feel free to remove the post from here. Oh and THANKS for the work you put into LASP. It is by far the best option I've found for what I'm doing.... just need to figure out how to mod it for output device instead of input.

Regards,

Aaron

**Comment by keijiro** [comment]
Building a feedback from an audio output endpoint to an audio input endpoint isn't generally supported with common audio APIs. You have to use some tricks to accomplish it.

- If you're trying to capture audio output from Unity, try LASP Loopback (a special build that supports audio loopback within Unity).
  https://github.com/keijiro/Lasp/tree/loopback
- If you're trying to capture audio output from other applications, you have to install a special loopback/virtual/null driver. Search on Google with "virtual audio driver" or something like that.
- Or you can just make a loopback connection in a physical form -- Plug a cable between an input jack and an output jack. Beware not to generate a howling sound.

**Comment by friken** [comment]
thanks for the reply. Yeah, I am needing audio output from other apps (anything playing through windows default audio output device). The FMOD wrapper called audiostream does this without a null driver but can't do so without latency as it is designed to pipe the raw data through unity audiosource... I can't tell how much lag is FMOD, vs the wrapper, vs unity audiosource getspectrumdata... all needed to do what I've gotten LASP to do with seemingly zero latency. 

The latency was so bad w the fmod wrapper mainly because it was never even consistent. Sometimes it would be almost fast enough to not notice... sometimes it would get behind several seconds to the source.... it also needed a different input and output since unity is doing the processing if you wanted the visual output to lookeven slightly in sync. 

Looking though the port audio docs, the stream says it supports audio input and output devices.... does that mean it only supports getting data from an input and only supports streaming data out to an output device?

**Comment by keijiro** [comment]
My advice here is -- don't trust PortAudio. It's super convenient but far from perfect. I ended up with reading the source code to implement LASP. I guess that it doesn't support your use-case.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
