### ISSUE TITLE
How do we convert the spectrum array into a frequency/note?

### ISSUE THREAD

**Issue by uneatenbreakfast** [keijiro/Lasp#70]
How do I convert the spectrum analyzer's spectrum into a single frequency or note?

**Comment by keijiro** [comment]
This library doesn't offer such a feature. You need another library for it.

**Comment by uneatenbreakfast** [comment]
Do you have any recommendations?

**Comment by keijiro** [comment]
Unfortunately, no. ChatGPT could give more useful advice than me (no kidding, this is a serious advice).
