### ISSUE TITLE
Multiple LASP Loopback streams?

### ISSUE THREAD

**Issue by jmaruska** [keijiro/Lasp#9]
Is there a way to use mixer groups to have multiple LASP streams?

It seems that if you have two mixer groups, each with a LASP Loopback effect applied, there is no way to differentiate the streams and they just get summed together.

**Comment by keijiro** [comment]
At the moment, LASP only supports single devide/channel input. It needs a total redesign to support multiple devices/channels, but yeah, I can understand that it should have it.

**Comment by jmaruska** [comment]
Wow - thanks for the quick response!

I'm working on a robotics project and wanted to use different audio streams to synchronize/augment with motor and lighting movements as well as gameObject transforms. 4-6 simultaneous streams would be ideal.

Fantastic work, by the way. I check your Tumblr daily and am continually blown away by what you do.

**Comment by jmaruska** [comment]
The Unity audio plugin sdk demo files include a routing effect that seems to do what I was looking for. Not sure what the latency is yet - but will keep playing with it.

[https://bitbucket.org/Unity-Technologies/nativeaudioplugins](https://bitbucket.org/Unity-Technologies/nativeaudioplugins)

**Comment by corbinyo** [comment]
@jmaruska How did this work out?
And if it did work out, could you possibly give an update on how you implemented?

Looking to take two audio signals through a mixer and assign to two LASP groups

**Comment by keijiro** [comment]
This issue is merged to #2
